// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Backend.API.Models
{
    [Table("produto")]
    public partial class Produto
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(40)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("preco", TypeName = "decimal(8, 2)")]
        public decimal Preco { get; set; }
        public DateTime? Validade { get; set; }
    }
}